[package]
name = "proton_agent_app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "proton"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["signal"] }
proton_agent_grpc = { path = "../grpc" }
console = "0.16.3"
clap = { version = "4", features = ["derive"] }
rustyline = "14"
anyhow = "1"
